import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/src/app/styles/globals.css";
import {NextUIProvider} from '@nextui-org/react';
import { ToolsBarStoreProvider } from "@/src/app/providers/tools-bar/tools-bar.provider";

const inter = localFont({
  src: [
    {
      path: './fonts/Inter-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/Inter-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/Inter-SemiBold.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: './fonts/Inter-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/Inter-Black.woff2',
      weight: '900',
      style: 'normal',
    }
  ]
});

export const metadata: Metadata = {
  title: "GLOW",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}`}
      >
        <NextUIProvider>
          <ToolsBarStoreProvider>
            {children}
          </ToolsBarStoreProvider>
        </NextUIProvider>
      </body>
    </html>
  );
}
