import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/src/app/styles/globals.css";
import { ThemeProvider, ToolsBarStoreProvider } from "@/src/app/providers";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const inter = localFont({
  src: [
    {
      path: './fonts/Inter-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/Inter-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/Inter-SemiBold.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: './fonts/Inter-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/Inter-Black.woff2',
      weight: '900',
      style: 'normal',
    }
  ]
});

export const metadata: Metadata = {
  title: "GLOW",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{ overflowX: "hidden" }}
        className={`${inter.className}`}
      >
        <AntdRegistry>
          <ThemeProvider>
            <ToolsBarStoreProvider>
              {children}
            </ToolsBarStoreProvider>
          </ThemeProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
